/**
 * Database Backup Script
 * Creates automated backups of the PostgreSQL database
 * Designed to run via GitHub Actions or cron jobs
 */

import { neon } from '@neondatabase/serverless';
import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';
import { format } from 'date-fns';

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  console.error('DATABASE_URL environment variable is required');
  process.exit(1);
}

async function createBackup() {
  console.log('Starting database backup...');

  try {
    const sql = neon(connectionString!); // Non-null assertion since we checked above
    const timestamp = format(new Date(), 'yyyy-MM-dd_HH-mm-ss');
    
    // Get all table names
    const tables = await sql`
      SELECT table_name 
      FROM information_schema.tables 
      WHERE table_schema = 'public' 
      ORDER BY table_name
    ` as { table_name: string }[];

    console.log(`Found ${tables.length} tables to backup`);

    // Create backup directory if it doesn't exist
    const backupDir = join(process.cwd(), 'backups');
    await mkdir(backupDir, { recursive: true });

    // Create backup filename
    const backupFile = join(backupDir, `backup_${timestamp}.sql`);

    // Export each table
    let backupContent = `-- Database Backup: ${timestamp}\n-- Generated by PolicyPulse CRM\n\n`;

    for (const table of tables) {
      const tableName = table.table_name;
      if (!tableName) continue;
      console.log(`Backing up table: ${tableName}`);

      // Get table data
      const data = await sql`SELECT * FROM ${sql(tableName)}`;

      backupContent += `\n-- Table: ${tableName}\n`;
      backupContent += `-- Records: ${data.length}\n`;
      
      // Convert to INSERT statements
      if (data.length > 0) {
        const columns = Object.keys(data[0]);
        backupContent += `INSERT INTO ${tableName} (${columns.join(', ')}) VALUES\n`;
        
        const values = data.map(row => {
          const rowValues = columns.map(col => {
            const val = row[col];
            if (val === null) return 'NULL';
            if (typeof val === 'string') return `'${val.replace(/'/g, "''")}'`;
            if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
            return val;
          });
          return `(${rowValues.join(', ')})`;
        });
        
        backupContent += values.join(',\n');
        backupContent += ';\n\n';
      }
    }

    // Write backup file
    await writeFile(backupFile, backupContent);
    console.log(`Backup created successfully: ${backupFile}`);

    // Keep only last 7 backups
    const fs = await import('fs');
    const files = await fs.promises.readdir(backupDir);
    const backupFiles = files
      .filter(f => f.startsWith('backup_') && f.endsWith('.sql'))
      .sort()
      .reverse();

    if (backupFiles.length > 7) {
      const filesToDelete = backupFiles.slice(7);
      for (const file of filesToDelete) {
        await fs.promises.unlink(join(backupDir, file));
        console.log(`Deleted old backup: ${file}`);
      }
    }

    console.log('Backup process completed successfully');
  } catch (error) {
    console.error('Backup failed:', error);
    process.exit(1);
  }
}

// Run backup
createBackup();
